version: 2.1
  
jobs:
  build-docs:
    docker:
      - image: runai/circleci-mkdocs:latest
    steps:
      - checkout
      - run:
          name: deploy-documentation
          command: mkdocs gh-deploy

workflows:
  version: 2.1
  deploy:
    jobs:
      - build-docs:
          name: build
          filters:
            branches:
              only:
                - omer-deploy-test
